export enum Width {
  ExtraSmall = 'xs',
  Small = 'sm',
  Medium = 'md',
  Large = 'lg',
  ExtraLarge = 'xl',
  TwoExtraLarge = '2xl',
  ThreeExtraLarge = '3xl',
  FourExtraLarge = '4xl',
  FiveExtraLarge = '5xl',
  SixExtraLarge = '6xl',
  SevenExtraLarge = '7xl',
  Full = 'full',
  MinContent = 'min',
  MaxContent = 'max',
  FitContent = 'fit',
  Prose = 'prose',
  ScreenSmall = 'screen-sm',
  ScreenMedium = 'screen-md',
  ScreenLarge = 'screen-lg',
  ScreenExtraLarge = 'screen-xl',
  ScreenTwoExtraLarge = 'screen-2xl',
  Screen = 'screen',
}
